stukdo/config/routes.rb
Rails.application.routes.draw do
  resources :tasks do 
    member do 
      put :change
    end
  end

  devise_for :users
  root 'pages#home'
  get '/about', to: 'pages#about'
  get '/test', to: 'pages#test'

end

stukdo/app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :user

  validates :user_id, presence: true
  validates :content, presence: true

  auto_html_for :content do 
    html_escape
    image
    youtube(:width => "100%", :height => 250, :autoplay => false)
    link :target => "_blank", :rel => "nofollow"
    simple_format
  end
end

stukdo/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :tasks, dependent: :destroy
end

stukdo/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

stukdo/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    if current_user
      redirect_to tasks_path
    end
  end

  def about
  end

  def test
  end
end

stukdo/app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_task, only: [:show, :edit, :update, :destroy, :change]

  respond_to :html

  def index
    @to_do = current_user.tasks.where(state: "to_do")
    @doing = current_user.tasks.where(state: "doing")
    @done = current_user.tasks.where(state: "done")
    respond_with(@tasks)
  end

  def show
    respond_with(@task)
  end

  def new
    @task = Task.new
    respond_with(@task)
  end

  def edit
  end

  def create
    @task = current_user.tasks.new(task_params)
    @task.save
    respond_with(@task)
  end

  def update
    @task.update(task_params)
    respond_with(@task)
  end

  def destroy
    @task.destroy
    respond_with(@task)
  end

  def change
    @task.update_attributes(state: params[:state])
    respond_to do |format|
      format.html {redirect_to tasks_path, notice: "Task Updated"}
    end
  end

  private
    def set_task
      @task = Task.find(params[:id])
    end

    def task_params
      params.require(:task).permit(:content, :state)
    end
end

stukdo/app/helpers/application_helper.rb
module ApplicationHelper
end

stukdo/app/helpers/pages_helper.rb
module PagesHelper
end

stukdo/app/helpers/tasks_helper.rb
module TasksHelper
end

stukdo/app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "<i class='fa fa-circle-o-notch'></i> Stukdo".html_safe, root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      
      
      <ul class="nav navbar-nav navbar-right">
      <% if current_user %>
        <li><%= link_to "Settings", edit_user_registration_path %></li>
        <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li><%= link_to "About", about_path %>
        <li><%= link_to "Login", new_user_session_path %></li>
      <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

stukdo/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Stukdo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render "layouts/header" %>
<div class="container">
<%= yield %>
</div>

</body>
</html>

stukdo/app/views/pages/about.html.erb
<h1>About Us</h1>
<p>Our vision is to improve people's productivity</p>

stukdo/app/views/pages/home.html.erb
<div class='jumbotron'>
  <h1><i class="fa fa-circle-o-notch"></i> Stukdo</h1>
  <p>This is my smart to do list Ruby on Rails application</p>
  <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary btn-lg"%>
</div>

stukdo/app/views/pages/test.html.erb
<div class="row">
  <div class="col-md-4"><h1 class="text-center">To Do</h1>
    <div class="panel panel-info">
      <div class="panel-heading">Heading</div>
      <div class="panel-body">Content</div>
      <div class="panel-footer text-center">Footer</div>
    </div>
  </div>
  <div class="col-md-4 text-center">
    <h1 class="text-center">Doing</h1>
  </div>
  <div class="col-md-4 text-center">
    <h1 class="text-center">Done</h1>
  </div>
</div>

stukdo/app/views/tasks/_form.html.erb
<%= simple_form_for(@task, html: {class: "form-signin"}) do |f| %>
  <%= f.error_notification %>
    <%= f.input :content, label: false, required: true, autofocus: true, input_html: {class: "form-control"}, placeholder: "Content" %>
    <%= f.button :submit, class: "btn btn-primary btn-block" %>
<% end %>

stukdo/app/views/tasks/_task.html.erb
<div class="panel panel-info">
  <div class="panel-heading">
    <%= link_to edit_task_path(task) do %>
      created <%= time_ago_in_words(task.created_at) %> ago
    <% end %>

    <%= link_to "x", task_path(task), method: :delete, data: {confirm: "Are you sure?"}, class: "pull-right" %>
  </div>
  <div class="panel-body">
    <% if task.content.include?("http") %>
      <%= raw(task.content_html) %>
    <% else %>
      <%= task.content %>
    <% end %>
  </div>
  <div class="panel-footer text-center">
    <% if task.state == "doing" %>
      <div class="btn-group btn-group-justified">
      <%= link_to "<i class='fa fa-arrow-left'></i>".html_safe, change_task_path(task, state: "to_do"), method: :put, class: "btn btn-info btn-md btn-block" %>
      <%= link_to "<i class='fa fa-arrow-right'></i>".html_safe, change_task_path(task, state: "done"), method: :put, class: "btn btn-info btn-md btn-block" %>
      </div>
    <% elsif task.state == "to_do" %>
      <%= link_to "<i class='fa fa-arrow-right'></i>".html_safe, change_task_path(task, state: "doing"), method: :put, class: "btn btn-info btn-md btn-block" %>
    <% else %>
      <%= link_to "<i class='fa fa-arrow-left'></i>".html_safe, change_task_path(task, state: "doing"), method: :put, class: "btn btn-info btn-md btn-block" %>
    <% end %>
  </div>
</div>

stukdo/app/views/tasks/edit.html.erb
<h1 class="text-center">Edit task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

stukdo/app/views/tasks/index.html.erb
<div class="row">
  <div class="col-md-4"><h1 class="text-center">To Do</h1>
    <%= render @to_do %>
  </div>
  <div class="col-md-4"><h1 class="text-center">Doing</h1>
  <%= render @doing %>
  </div>
  <div class="col-md-4"><h1 class="text-center">Done</h1>
    <%= render @done %>
  </div>
</div>

<br>
<%= link_to 'New Task', new_task_path %>

stukdo/app/views/tasks/new.html.erb
<h1 class="text-center">New task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

stukdo/app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @task.content %>
</p>
<p>
  <strong>State:</strong>
  <%= @task.state %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>